### ISSUE TITLE
Table_CollectionTree::findPairsForSelectForm() has a useless parameter

### ISSUE THREAD

**Issue by teo1978** [omeka/plugin-CollectionTree#27]
This is a bug in the source code and its documentation that has no effect in practice, other than misleading those who may read the code documentation.

In the method `Table_CollectionTree::findPairsForSelectForm() `:

```
/**
     * Return the collection tree hierarchy as a one-dimensional array.
     *
     * @param array $options (optional) Set of parameters for searching/
     * filtering results.
     * @param string $padding The string representation of the collection depth.
     * @return array
     */
    public function findPairsForSelectForm(array $options = array(), $padding = '-')
    {
        if (isset($params['padding'])) {
            $padding = $params['padding'];
        } else {
            $padding = '-';
        }
        $options = array(); /////////////////////////////////  <<<<<<<<<< THIS
     
        //.....
```

The first parameter, `$options`, is completely unused, as it's overwritten with an empty array before it's ever used. No matter what you pass to the method in this parameter, it will have no effect whatsoever.

More importantly, the documentation for the parameter doesn't say so:
```
/*
     * @param array $options (optional) Set of parameters for searching/
     * filtering results.
...
*/
```

Whatever that is supposed to mean, it's not true, as the argument has no effect.

**Comment by zerocrates** [comment]
The parameter `$options` must be present as this method is an override of the base Table class's method, which has the parameter. So it's illegal to omit it.

The `$options` array inside the method is actually referring to options as in the HTML `<option>` element... this is not the greatest naming in the world, for sure. The `$options` parameter got added to fix the signature quite some time ago, and when it was added, the standard comment for that parameter got copied over from the base class.

Since CollectionTree's implementation respects no options, the parameter documentation should say so.
